server:
  port: 8081

spring:
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

  jpa:
    show-sql: false  # SQL ?? ?? ?? ????
    properties:
      hibernate:
        format_sql: false  # ??? SQL ?? ????

logging:
  level:
    org.hibernate.SQL: WARN   # Hibernate SQL ?? ?? ????
    org.hibernate.type.descriptor.sql.BasicBinder: WARN  # Hibernate ??? ?? ????
    com.settlement.project.batch: INFO  # Batch ?? ?? ??? INFO ??? ??
